services:
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
  app:
    image: ${IMAGE_APP_TAG}
    depends_on:
      - mysql
    build: ./
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL_PROD}
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes: 
  db:
