services:
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=energy
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
  app:
    depends_on:
      - mysql
    build: ./
    ports:
      - 3000:3000
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes: 
  db:

